// react-task-tracker/src/App.vue
<script setup>
import AppHeader from "./components/AppHeader.vue";
import AppFooter from "./components/AppFooter.vue";
import { state } from "./state";

// Fetch tasks
async function fetchTasks() {
	const res = await fetch("http://localhost:5000/tasks");
	const data = await res.json();
	return data;
}

// Initially Load in Tasks
(async () => {
	const tasksFromServer = await fetchTasks();
	state.tasks = tasksFromServer;
})();
</script>

<template>
	<div class="container">
		<AppHeader
			@add="state.showAddTask = !state.showAddTask"
			:showAdd="state.showAddTask"
		/>
		<router-view />
		<AppFooter />
	</div>
</template>

// react-task-tracker/src/App.js
import Header from "./components/Header";
import Tasks from "./components/Tasks";
import AddTask from "./components/AddTask";
import Footer from "./components/Footer";
import About from "./components/About";

import { useEffect, useState } from "react";
import { BrowserRouter as Router, Route, Routes } from "react-router-dom";

function App() {
	const [tasks, setTasks] = useState([]);
	const [showAddTask, setShowAddTask] = useState(false);

	// Initially Load in Tasks
	useEffect(() => {
		const getTasks = async () => {
			const tasksFromServer = await fetchTasks();
			setTasks(tasksFromServer);
		};

		getTasks();
	}, []);

	// Fetch tasks
	const fetchTasks = async () => {
		const res = await fetch("http://localhost:5000/tasks");
		const data = await res.json();

		return data;
	};

	// Fetch task
	const fetchTask = async (id) => {
		const res = await fetch(`http://localhost:5000/tasks/${id}`);
		const data = await res.json();

		return data;
	};

	// Add Task
	const addTask = async (task) => {
		const res = await fetch(`http://localhost:5000/tasks`, {
			method: "POST",
			headers: {
				"Content-type": "application/json",
			},
			body: JSON.stringify(task),
		});

		const data = await res.json();
		setTasks([...tasks, data]);
	};

	// Delete Task
	const deleteTask = async (id) => {
		await fetch(`http://localhost:5000/tasks/${id}`, {
			method: "DELETE",
		});

		// console.log("delete", id);

		setTasks(tasks.filter((task) => task.id !== id));
	};

	// Toggle Reminder
	const toggleReminder = async (id) => {
		// console.log("reminder", id);
		// setTasks(
		// 	tasks.map((task) =>
		// 		task.id === id ? { ...task, reminder: !task.reminder } : task
		// 	)
		// );

		const taskToToggle = await fetchTask(id);
		const updTask = { ...taskToToggle, reminder: !taskToToggle.reminder };

		const res = await fetch(`http://localhost:5000/tasks/${id}`, {
			method: "PUT",
			headers: {
				"Content-type": "application/json",
			},
			body: JSON.stringify(updTask),
		});

		const data = await res.json();

		setTasks(
			tasks.map((task) =>
				task.id === id ? { ...task, reminder: data.reminder } : task
			)
		);
	};

	return (
		<Router>
			<div className="container">
				<Header
					onAdd={() => setShowAddTask(!showAddTask)}
					showAdd={showAddTask}
				/>

				<Routes>
					<Route
						path="/"
						exact
						element={
							<>
								{showAddTask && <AddTask onAdd={addTask} />}
								{tasks.length > 0 ? (
									<Tasks
										tasks={tasks}
										onDelete={deleteTask}
										onToggle={toggleReminder}
									/>
								) : (
									"No Tasks to Show"
								)}
							</>
						}
					/>
					<Route path="about" element={<About />} />
				</Routes>

				<Footer />
			</div>
		</Router>
	);
}

export default App;
// https://www.youtube.com/watch?v=w7ejDZ8SWv8
